title: TechnoQueers
email: technoqueersny@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A weekly guide for the techno-curious
baseurl: ''
basecolor: '#000000' # for browser settings
url: 'https://technoqueers.com'
twitter_username: TechnoQueersNY
github_username: 
facebook_username: technoqueers

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock